In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
new_arr = arr+100

In [13]:
new_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:]=88

In [19]:
slice_of_arr

array([88, 88, 88, 88, 88, 88])

In [20]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [21]:
copy_of_array = arr.copy()

In [22]:
copy_of_array[:]=100

In [23]:
copy_of_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d.shape

(3, 3)

In [33]:
arr_2d[1]

array([20, 25, 30])

In [34]:
arr_2d[1][1]

25

In [35]:
arr_2d[1,1]

25

In [40]:
arr_2d[2,2]

45

In [42]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [43]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
bool_arr = arr>4

In [48]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])