In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'1.1.0'

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [11]:
x = torch.from_numpy(arr)

In [12]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
type(x)

torch.Tensor

In [14]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [16]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [17]:
x.dtype

torch.int32

In [18]:
arr2d = np.arange(0.0,12.0)

In [19]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
arr2d = arr2d.reshape(4,3)

In [21]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [23]:
x2 = torch.from_numpy(arr2d)

In [24]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [27]:
arr[0] = 99

In [28]:
arr

array([99,  2,  3,  4,  5])

In [29]:
my_arr = np.arange(0,10)

In [30]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_tensor = torch.tensor(my_arr)

In [32]:
my_other_tensor = torch.from_numpy(my_arr)

In [33]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [34]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [35]:
my_arr[0] = 9999

In [36]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [37]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

In [38]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [5]:
new_arr = np.array([1,2,3])

In [6]:
new_arr.dtype

dtype('int32')

In [7]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
my_tensor = torch.Tensor(new_arr)

In [10]:
my_tensor

tensor([1., 2., 3.])

In [11]:
my_tensor.dtype

torch.float32

In [13]:
torch.empty(4,2)

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [6.8996e-07, 6.6453e-07]])

In [14]:
torch.zeros(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
torch.zeros(4,2,dtype=torch.int64)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [16]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [18]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [19]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [22]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [23]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [24]:
my_tensor =  torch.tensor([1,2,3])

In [25]:
my_tensor.dtype

torch.int64

In [26]:
my_tensor = my_tensor.type(torch.int32)

In [27]:
my_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
my_tensor.dtype

torch.int32

In [29]:
torch.rand(4,3)

tensor([[0.7891, 0.9660, 0.3784],
        [0.7309, 0.0099, 0.8534],
        [0.6487, 0.4568, 0.9687],
        [0.0792, 0.8071, 0.4307]])

In [30]:
torch.randn(4,3)

tensor([[ 1.0630,  0.0495,  0.2923],
        [ 0.4817, -0.1372, -1.7687],
        [-0.4536,  1.2413,  0.3623],
        [ 0.2802, -0.8401,  0.4988]])

In [31]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[7, 0, 6, 4, 9],
        [1, 2, 3, 7, 5],
        [7, 8, 3, 3, 3],
        [1, 0, 0, 0, 9],
        [1, 5, 3, 4, 9]])

In [32]:
x = torch.zeros(2,5)

In [33]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [34]:
torch.rand_like(x)

tensor([[0.1303, 0.9427, 0.4292, 0.6755, 0.9296],
        [0.6797, 0.7342, 0.9324, 0.2677, 0.9308]])

In [35]:
torch.randn_like(x)

tensor([[-0.6385,  0.2758, -0.1127, -0.1843,  0.8586],
        [-0.6043, -2.5807,  0.0301,  0.9083, -1.4609]])

In [37]:
torch.randint_like(x,low=0,high=11)

tensor([[ 3.,  4.,  3.,  5., 10.],
        [ 5.,  9.,  4.,  9.,  0.]])

In [39]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])