In [1]:
import torch
import numpy as np

In [2]:
x=torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:

x[1,1]

tensor(3)

In [5]:
#indexing the column
x[:,1]

tensor([1, 3, 5])

In [6]:
#to retain the shape use slicing
x[:,1:]


tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = x.reshape(2,5)

In [14]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x = torch.arange(10)

In [18]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.shape

torch.Size([10])

In [22]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
z = x.view(2,5)

In [25]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
x[0]=8888

In [27]:
x

tensor([8888,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [28]:
z

tensor([[8888,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [29]:
x = torch.arange(10)

In [30]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x.shape

torch.Size([10])

In [37]:
#infer what 2nd dimension should be
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [38]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
a = torch.tensor([1.,2.,3.])

In [40]:
b =  torch.tensor([4.,5.,6.])

In [42]:
a

tensor([1., 2., 3.])

In [43]:
a.dtype

torch.float32

In [44]:
b

tensor([4., 5., 6.])

In [45]:
b.dtype

torch.float32

In [46]:
a + b

tensor([5., 7., 9.])

In [47]:
torch.add(a,b)

tensor([5., 7., 9.])

In [48]:
a.mul(b)
#a = a + b

tensor([ 4., 10., 18.])

In [49]:
a

tensor([1., 2., 3.])

In [50]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [51]:
a

tensor([ 4., 10., 18.])

In [52]:
a = torch.tensor([1.,2.,3.])

In [54]:
b =  torch.tensor([4.,5.,6.])

In [55]:
a

tensor([1., 2., 3.])

In [56]:
b

tensor([4., 5., 6.])

In [57]:
#ELEMENTS BY ELEMENTS MULTIPLICATION
a*b

tensor([ 4., 10., 18.])

In [58]:
#there are 2 multiplication: dot product & 2Dimension multiplicatiom
#basic math

#true dor product:
a.dot(b)

tensor(32.)

In [61]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [62]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [63]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [64]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [65]:
a.shape

torch.Size([2, 3])

In [66]:
b.shape

torch.Size([3, 2])

In [67]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [68]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [69]:
x = torch.tensor([2.,3.,4.,5.])

In [70]:
x

tensor([2., 3., 4., 5.])

In [71]:
#euclidian
x.norm()

tensor(7.3485)

In [72]:
#grab num of element
x.numel()

4

In [73]:
len(a)

2

In [74]:
#total number of elements
a.numel()

6