In [1]:
import torch

In [4]:
# Function:𝑦=2𝑥4+𝑥3+3𝑥2+5𝑥+1

# Derivative: 𝑦′=8𝑥3+3𝑥2+6𝑥+5

x = torch.tensor(2.0,requires_grad=True)
#This sets up computational tracking on the tensor so that Pytorch can keep an eye on that tensor


In [5]:
#Define a fn (normal polynomial fn)
y =  2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [6]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [7]:
type(y)

torch.Tensor

In [8]:
#this perform backpropagation
y.backward()

In [9]:
x.grad
#the result 93 is the value of derivative

tensor(93.)

In [10]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]],requires_grad=True)

In [11]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [12]:
y = 3*x + 2

In [13]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [16]:
z = 2*y**2

In [17]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [18]:
#set output to be the matrix mean
out = z.mean()

In [19]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [20]:
#perfprm backpropagation to find gradient of x with respect to out layer
out.backward()

In [21]:
#the x.grad auto calculate the partia; derivative of o with respect to x (applies chain rule)

print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
