In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#--------------------------------Get Text Data------------------------------
with open('../Data/shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [4]:
type(text)

str

In [5]:
text[:1000] #1st 1k char --raw str

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bud buriest thy content,\n  And tender churl mak'st waste in niggarding:\n    Pity the world, or else this glutton be,\n    To eat the world's due, by the grave and thee.\n\n\n                     2\n  When forty winters shall besiege thy brow,\n  And dig deep trenches in thy beauty's field,\n  Thy youth's proud livery so gazed on now,\n  Will be a tattered weed of small worth held:  \n  Then being asked, where all thy beauty lies,\n  Where all the treasure of thy lusty days;\n  To sa

In [6]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [7]:
len(text)

5445609

In [8]:
#----------------------------------Encode Entire Text-----------------------
#Figure out all unique characters in the text
all_characters = set(text)

In [9]:
all_characters

{'\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}'}

In [10]:
len(all_characters) #total 84 unique char

84

In [11]:
#Encoder will take a char & returns its encoded number
#Decoder would do the opposite

In [13]:
#enumerate(all_characters) would assign number to unique char
for pair in enumerate(all_characters):
    print(pair)

(0, '>')
(1, 'G')
(2, 'x')
(3, 't')
(4, ':')
(5, ',')
(6, '.')
(7, '[')
(8, '!')
(9, 'k')
(10, 'm')
(11, 'w')
(12, 'f')
(13, 'j')
(14, 'n')
(15, '2')
(16, 'Y')
(17, 'q')
(18, '?')
(19, 'o')
(20, 'r')
(21, 'u')
(22, 'l')
(23, 'd')
(24, ' ')
(25, '9')
(26, 'P')
(27, ';')
(28, 'h')
(29, '5')
(30, 'Z')
(31, "'")
(32, '7')
(33, 'A')
(34, '&')
(35, 'v')
(36, 'i')
(37, 'b')
(38, ')')
(39, '<')
(40, 'D')
(41, 'J')
(42, 'F')
(43, '"')
(44, '`')
(45, '}')
(46, 'X')
(47, 'Q')
(48, 'H')
(49, 'O')
(50, 'B')
(51, ']')
(52, '_')
(53, 'z')
(54, '4')
(55, 'I')
(56, '(')
(57, '3')
(58, 'c')
(59, 'K')
(60, '-')
(61, '0')
(62, 'V')
(63, '|')
(64, 'N')
(65, 'R')
(66, 'y')
(67, 'S')
(68, 'T')
(69, '\n')
(70, 'L')
(71, 'e')
(72, 'E')
(73, 's')
(74, 'M')
(75, 'C')
(76, '8')
(77, 'g')
(78, 'p')
(79, '6')
(80, '1')
(81, 'U')
(82, 'a')
(83, 'W')


In [18]:
# num --> Letter
decoder = dict(enumerate(all_characters))

In [19]:
decoder

{0: '>',
 1: 'G',
 2: 'x',
 3: 't',
 4: ':',
 5: ',',
 6: '.',
 7: '[',
 8: '!',
 9: 'k',
 10: 'm',
 11: 'w',
 12: 'f',
 13: 'j',
 14: 'n',
 15: '2',
 16: 'Y',
 17: 'q',
 18: '?',
 19: 'o',
 20: 'r',
 21: 'u',
 22: 'l',
 23: 'd',
 24: ' ',
 25: '9',
 26: 'P',
 27: ';',
 28: 'h',
 29: '5',
 30: 'Z',
 31: "'",
 32: '7',
 33: 'A',
 34: '&',
 35: 'v',
 36: 'i',
 37: 'b',
 38: ')',
 39: '<',
 40: 'D',
 41: 'J',
 42: 'F',
 43: '"',
 44: '`',
 45: '}',
 46: 'X',
 47: 'Q',
 48: 'H',
 49: 'O',
 50: 'B',
 51: ']',
 52: '_',
 53: 'z',
 54: '4',
 55: 'I',
 56: '(',
 57: '3',
 58: 'c',
 59: 'K',
 60: '-',
 61: '0',
 62: 'V',
 63: '|',
 64: 'N',
 65: 'R',
 66: 'y',
 67: 'S',
 68: 'T',
 69: '\n',
 70: 'L',
 71: 'e',
 72: 'E',
 73: 's',
 74: 'M',
 75: 'C',
 76: '8',
 77: 'g',
 78: 'p',
 79: '6',
 80: '1',
 81: 'U',
 82: 'a',
 83: 'W'}

In [20]:
#Letter --> num
encoder = {char: ind for ind,char in decoder.items()}

In [21]:
encoder

{'>': 0,
 'G': 1,
 'x': 2,
 't': 3,
 ':': 4,
 ',': 5,
 '.': 6,
 '[': 7,
 '!': 8,
 'k': 9,
 'm': 10,
 'w': 11,
 'f': 12,
 'j': 13,
 'n': 14,
 '2': 15,
 'Y': 16,
 'q': 17,
 '?': 18,
 'o': 19,
 'r': 20,
 'u': 21,
 'l': 22,
 'd': 23,
 ' ': 24,
 '9': 25,
 'P': 26,
 ';': 27,
 'h': 28,
 '5': 29,
 'Z': 30,
 "'": 31,
 '7': 32,
 'A': 33,
 '&': 34,
 'v': 35,
 'i': 36,
 'b': 37,
 ')': 38,
 '<': 39,
 'D': 40,
 'J': 41,
 'F': 42,
 '"': 43,
 '`': 44,
 '}': 45,
 'X': 46,
 'Q': 47,
 'H': 48,
 'O': 49,
 'B': 50,
 ']': 51,
 '_': 52,
 'z': 53,
 '4': 54,
 'I': 55,
 '(': 56,
 '3': 57,
 'c': 58,
 'K': 59,
 '-': 60,
 '0': 61,
 'V': 62,
 '|': 63,
 'N': 64,
 'R': 65,
 'y': 66,
 'S': 67,
 'T': 68,
 '\n': 69,
 'L': 70,
 'e': 71,
 'E': 72,
 's': 73,
 'M': 74,
 'C': 75,
 '8': 76,
 'g': 77,
 'p': 78,
 '6': 79,
 '1': 80,
 'U': 81,
 'a': 82,
 'W': 83}

In [22]:
#ensure encoder & decoder match -->represent the same char with num

In [23]:
# take all txt & encode it so it has numerical info aspect to it
encoded_text = np.array([encoder[char] for char in text])

In [24]:
encoded_text[:500]

array([69, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 80, 69, 24, 24, 42, 20, 19, 10, 24, 12, 82, 36,
       20, 71, 73,  3, 24, 58, 20, 71, 82,  3, 21, 20, 71, 73, 24, 11, 71,
       24, 23, 71, 73, 36, 20, 71, 24, 36, 14, 58, 20, 71, 82, 73, 71,  5,
       69, 24, 24, 68, 28, 82,  3, 24,  3, 28, 71, 20, 71, 37, 66, 24, 37,
       71, 82, 21,  3, 66, 31, 73, 24, 20, 19, 73, 71, 24, 10, 36, 77, 28,
        3, 24, 14, 71, 35, 71, 20, 24, 23, 36, 71,  5, 69, 24, 24, 50, 21,
        3, 24, 82, 73, 24,  3, 28, 71, 24, 20, 36, 78, 71, 20, 24, 73, 28,
       19, 21, 22, 23, 24, 37, 66, 24,  3, 36, 10, 71, 24, 23, 71, 58, 71,
       82, 73, 71,  5, 69, 24, 24, 48, 36, 73, 24,  3, 71, 14, 23, 71, 20,
       24, 28, 71, 36, 20, 24, 10, 36, 77, 28,  3, 24, 37, 71, 82, 20, 24,
       28, 36, 73, 24, 10, 71, 10, 19, 20, 66,  4, 69, 24, 24, 50, 21,  3,
       24,  3, 28, 19, 21, 24, 58, 19, 14,  3, 20, 82, 58,  3, 71, 23, 24,
        3, 19, 24,  3, 28

In [25]:
#----------------------------One Hot Encoding-------------------------------
#we need to one-hot encode our data inorder for it to work with the network structure. 
def one_hot_encoder(encoded_text, num_uni_chars):
    #encode_text --> batch of encoded text
    #num_uni_chars --> len(set(text))
    
    
    '''
    encoded_text : batch of encoded text
    
    num_uni_chars = number of unique characters (len(set(text)))
    '''
    
    # METHOD FROM:
    # https://stackoverflow.com/questions/29831489/convert-encoded_textay-of-indices-to-1-hot-encoded-numpy-encoded_textay
      
    # Create a placeholder for zeros.
    one_hot = np.zeros((encoded_text.size, num_uni_chars))
    
    # Convert data type for later use with pytorch (errors if we dont!)
    one_hot = one_hot.astype(np.float32)

    # Using fancy indexing fill in the 1s at the correct index locations
    one_hot[np.arange(one_hot.shape[0]), encoded_text.flatten()] = 1.0
    

    # Reshape it so it matches the batch sahe
    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_chars))
    
    return one_hot

In [28]:
arr = np.array([1,2,0])

In [29]:
arr

array([1, 2, 0])

In [30]:
one_hot_encoder(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
#----------------------------Creating Training Batches----------------------
