In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#--------------------------------Get Text Data------------------------------
with open('../Data/shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [4]:
type(text)

str

In [5]:
text[:1000] #1st 1k char --raw str

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bud buriest thy content,\n  And tender churl mak'st waste in niggarding:\n    Pity the world, or else this glutton be,\n    To eat the world's due, by the grave and thee.\n\n\n                     2\n  When forty winters shall besiege thy brow,\n  And dig deep trenches in thy beauty's field,\n  Thy youth's proud livery so gazed on now,\n  Will be a tattered weed of small worth held:  \n  Then being asked, where all thy beauty lies,\n  Where all the treasure of thy lusty days;\n  To sa

In [6]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [7]:
len(text)

5445609

In [8]:
#----------------------------------Encode Entire Text-----------------------
#Figure out all unique characters in the text
all_characters = set(text)

In [9]:
all_characters

{'\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}'}

In [10]:
len(all_characters) #total 84 unique char

84

In [11]:
#Encoder will take a char & returns its encoded number
#Decoder would do the opposite

In [12]:
#enumerate(all_characters) would assign number to unique char
for pair in enumerate(all_characters):
    print(pair)

(0, '.')
(1, 'm')
(2, '7')
(3, '8')
(4, '[')
(5, '(')
(6, '|')
(7, '-')
(8, 'n')
(9, '?')
(10, 'r')
(11, 'd')
(12, 'v')
(13, 'J')
(14, 'O')
(15, '}')
(16, 'p')
(17, 'b')
(18, 'S')
(19, '_')
(20, '0')
(21, 'D')
(22, 'L')
(23, 'q')
(24, '&')
(25, 'j')
(26, 'I')
(27, 'w')
(28, 'G')
(29, 'l')
(30, '>')
(31, 'P')
(32, "'")
(33, '"')
(34, '3')
(35, ')')
(36, 't')
(37, 'R')
(38, 'x')
(39, '2')
(40, 'k')
(41, 'U')
(42, 'Z')
(43, '1')
(44, 'a')
(45, '4')
(46, 'T')
(47, 'u')
(48, ' ')
(49, ']')
(50, 'c')
(51, 'y')
(52, '!')
(53, 'M')
(54, 'V')
(55, 'i')
(56, 'H')
(57, '<')
(58, ':')
(59, 'A')
(60, ';')
(61, 'B')
(62, 'C')
(63, 'X')
(64, '`')
(65, '9')
(66, '\n')
(67, 's')
(68, 'f')
(69, 'K')
(70, 'N')
(71, 'h')
(72, 'z')
(73, 'Q')
(74, 'g')
(75, 'o')
(76, 'W')
(77, 'Y')
(78, 'F')
(79, 'e')
(80, ',')
(81, 'E')
(82, '5')
(83, '6')


In [13]:
# num --> Letter
decoder = dict(enumerate(all_characters))

In [14]:
decoder

{0: '.',
 1: 'm',
 2: '7',
 3: '8',
 4: '[',
 5: '(',
 6: '|',
 7: '-',
 8: 'n',
 9: '?',
 10: 'r',
 11: 'd',
 12: 'v',
 13: 'J',
 14: 'O',
 15: '}',
 16: 'p',
 17: 'b',
 18: 'S',
 19: '_',
 20: '0',
 21: 'D',
 22: 'L',
 23: 'q',
 24: '&',
 25: 'j',
 26: 'I',
 27: 'w',
 28: 'G',
 29: 'l',
 30: '>',
 31: 'P',
 32: "'",
 33: '"',
 34: '3',
 35: ')',
 36: 't',
 37: 'R',
 38: 'x',
 39: '2',
 40: 'k',
 41: 'U',
 42: 'Z',
 43: '1',
 44: 'a',
 45: '4',
 46: 'T',
 47: 'u',
 48: ' ',
 49: ']',
 50: 'c',
 51: 'y',
 52: '!',
 53: 'M',
 54: 'V',
 55: 'i',
 56: 'H',
 57: '<',
 58: ':',
 59: 'A',
 60: ';',
 61: 'B',
 62: 'C',
 63: 'X',
 64: '`',
 65: '9',
 66: '\n',
 67: 's',
 68: 'f',
 69: 'K',
 70: 'N',
 71: 'h',
 72: 'z',
 73: 'Q',
 74: 'g',
 75: 'o',
 76: 'W',
 77: 'Y',
 78: 'F',
 79: 'e',
 80: ',',
 81: 'E',
 82: '5',
 83: '6'}

In [15]:
#Letter --> num
encoder = {char: ind for ind,char in decoder.items()}

In [16]:
encoder

{'.': 0,
 'm': 1,
 '7': 2,
 '8': 3,
 '[': 4,
 '(': 5,
 '|': 6,
 '-': 7,
 'n': 8,
 '?': 9,
 'r': 10,
 'd': 11,
 'v': 12,
 'J': 13,
 'O': 14,
 '}': 15,
 'p': 16,
 'b': 17,
 'S': 18,
 '_': 19,
 '0': 20,
 'D': 21,
 'L': 22,
 'q': 23,
 '&': 24,
 'j': 25,
 'I': 26,
 'w': 27,
 'G': 28,
 'l': 29,
 '>': 30,
 'P': 31,
 "'": 32,
 '"': 33,
 '3': 34,
 ')': 35,
 't': 36,
 'R': 37,
 'x': 38,
 '2': 39,
 'k': 40,
 'U': 41,
 'Z': 42,
 '1': 43,
 'a': 44,
 '4': 45,
 'T': 46,
 'u': 47,
 ' ': 48,
 ']': 49,
 'c': 50,
 'y': 51,
 '!': 52,
 'M': 53,
 'V': 54,
 'i': 55,
 'H': 56,
 '<': 57,
 ':': 58,
 'A': 59,
 ';': 60,
 'B': 61,
 'C': 62,
 'X': 63,
 '`': 64,
 '9': 65,
 '\n': 66,
 's': 67,
 'f': 68,
 'K': 69,
 'N': 70,
 'h': 71,
 'z': 72,
 'Q': 73,
 'g': 74,
 'o': 75,
 'W': 76,
 'Y': 77,
 'F': 78,
 'e': 79,
 ',': 80,
 'E': 81,
 '5': 82,
 '6': 83}

In [17]:
#ensure encoder & decoder match -->represent the same char with num

In [18]:
# take all txt & encode it so it has numerical info aspect to it
encoded_text = np.array([encoder[char] for char in text])

In [19]:
encoded_text[:500]

array([66, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
       48, 48, 48, 48, 48, 43, 66, 48, 48, 78, 10, 75,  1, 48, 68, 44, 55,
       10, 79, 67, 36, 48, 50, 10, 79, 44, 36, 47, 10, 79, 67, 48, 27, 79,
       48, 11, 79, 67, 55, 10, 79, 48, 55,  8, 50, 10, 79, 44, 67, 79, 80,
       66, 48, 48, 46, 71, 44, 36, 48, 36, 71, 79, 10, 79, 17, 51, 48, 17,
       79, 44, 47, 36, 51, 32, 67, 48, 10, 75, 67, 79, 48,  1, 55, 74, 71,
       36, 48,  8, 79, 12, 79, 10, 48, 11, 55, 79, 80, 66, 48, 48, 61, 47,
       36, 48, 44, 67, 48, 36, 71, 79, 48, 10, 55, 16, 79, 10, 48, 67, 71,
       75, 47, 29, 11, 48, 17, 51, 48, 36, 55,  1, 79, 48, 11, 79, 50, 79,
       44, 67, 79, 80, 66, 48, 48, 56, 55, 67, 48, 36, 79,  8, 11, 79, 10,
       48, 71, 79, 55, 10, 48,  1, 55, 74, 71, 36, 48, 17, 79, 44, 10, 48,
       71, 55, 67, 48,  1, 79,  1, 75, 10, 51, 58, 66, 48, 48, 61, 47, 36,
       48, 36, 71, 75, 47, 48, 50, 75,  8, 36, 10, 44, 50, 36, 79, 11, 48,
       36, 75, 48, 36, 71

In [20]:
#----------------------------One Hot Encoding-------------------------------
#we need to one-hot encode our data inorder for it to work with the network structure. 
def one_hot_encoder(encoded_text, num_uni_chars):
    #encode_text --> batch of encoded text
    #num_uni_chars --> len(set(text))
    
    
    '''
    encoded_text : batch of encoded text
    
    num_uni_chars = number of unique characters (len(set(text)))
    '''
    
    # METHOD FROM:
    # https://stackoverflow.com/questions/29831489/convert-encoded_textay-of-indices-to-1-hot-encoded-numpy-encoded_textay
      
    # Create a placeholder for zeros.
    one_hot = np.zeros((encoded_text.size, num_uni_chars))
    
    # Convert data type for later use with pytorch (errors if we dont!)
    one_hot = one_hot.astype(np.float32)

    # Using fancy indexing fill in the 1s at the correct index locations
    one_hot[np.arange(one_hot.shape[0]), encoded_text.flatten()] = 1.0
    

    # Reshape it so it matches the batch sahe
    one_hot = one_hot.reshape((*encoded_text.shape, num_uni_chars))
    
    return one_hot

In [21]:
arr = np.array([1,2,0])

In [22]:
arr

array([1, 2, 0])

In [23]:
one_hot_encoder(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [24]:
#----------------------------Creating Training Batches----------------------
#create a function that will generate batches of characters along with the next character in the sequence as a label
example_text = np.arange(10)

In [25]:
example_text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# If we wanted 5 batches
example_text.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    
    '''
    Generate (using yield) batches for training.
    
    X: Encoded Text of length seq_len
    Y: Encoded Text shifted by one
    
    Example:
    
    X:
    
    [[1 2 3]]
    
    Y:
    
    [[ 2 3 4]]
    
    encoded_text : Complete Encoded Text to make batches from
    batch_size : Number of samples per batch
    seq_len : Length of character sequence
       
    '''
    
    # Total number of characters per batch
    # Example: If samp_per_batch is 2 and seq_len is 50, then 100
    # characters come out per batch.
    char_per_batch = samp_per_batch * seq_len
    
    
    # Number of batches available to make
    # Use int() to roun to nearest integer
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # Cut off end of encoded_text that
    # won't fit evenly into a batch
    encoded_text = encoded_text[:num_batches_avail * char_per_batch]
    
    
    # Reshape text into rows the size of a batch
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    

    # Go through each row in array.
    for n in range(0, encoded_text.shape[1], seq_len):
        
        # Grab feature characters
        x = encoded_text[:, n:n+seq_len]
        
        # y is the target shifted over by 1
        y = np.zeros_like(x)
       
        #
        try:
            y[:, :-1] = x[:, 1:]
            y[:, -1]  = encoded_text[:, n+seq_len]
            
        # FOR POTENTIAL INDEXING ERROR AT THE END    
        except:
            y[:, :-1] = x[:, 1:]
            y[:, -1] = encoded_text[:, 0]
            
        yield x, y

In [34]:
#----------------------Example of generating a batch-----------------------
sample_text = np.arange(20)

In [35]:
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5)

In [37]:
# Grab first batch
x, y = next(batch_generator)

In [38]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [39]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])